runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.config.py -b :$PORT app.index:app
service: abakus-api

skip_files:
  - .venv

#network:
#  name: elasticsearch
#  forwarded_ports:
#    - 80/tcp

resources:
  cpu: 2
  memory_gb: 8

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4

env_variables:
  ELASTICSEARCH_HOSTS: '10.142.0.7:9200,10.142.0.8:9200'
  API_DOC_LOCATION: 'https://sinuous-tine-156112.appspot.com/api'
